resolver: lts-8.5
flags:
  lnforum-yesod:
    library-only: false
    dev: false
allow-newer: true
packages:
- .
- ../lnforum-lib
- ../lnforum-sanitize
- ../lnforum-validate
- ../lnforum-types-gen
- ../haskell-api-helpers-shared
- ../haskell-either-helpers
- ../haskell-ebyam
- ../haskell-rehtie
- ../haskell-ifte
- ../stm-lifted
- ../yesod-auth-oauth2
extra-deps:
- html-entities-1.1.4.2
- random-extras-0.19
- serversession-backend-persistent-1.0.4
- load-env-0.1.1
