flags:
  lnforum-yesod:
    library-only: false
    dev: false
packages:
- .
- ../ln-lib
- ../lnforum-sanitize
- ../lnforum-validate
- ../haskell-api-helpers-shared
- ../haskell-lnforum-types
- ../haskell-either-helpers
- ../haskell-ebyam
- ../haskell-rehtie
- ../haskell-ifte
- ../stm-lifted
- ../yesod-auth-oauth2
extra-deps:
- html-entities-1.1.4
- random-extras-0.19
- serversession-backend-persistent-1.0.3
- load-env-0.1.1
resolver: lts-8.5
