#!/bin/bash

[ $# == 13 ] || { echo 'usage: post <resource_id> <data> <title> <description> <section> <page> <examples> <strengths> <categories> <splits> <substitutions> <tags> <style>' && exit 1; }

curlx-json resources/$1/leurons -d "{ \
    \"data\":\"${2}\" \
    \"title\":\"${3}\", \
    \"desc\":\"${4}\", \
    \"section\":\"${5}\", \
    \"page\":\"${6}\", \
    \"examples\":\"${7}\", \
    \"strengths\":\"${8}\", \
    \"categories\":\"${9}\", \
    \"splits\":\"${10}\", \
    \"subs\":\"${11}\", \
    \"tags\":\"${12}\", \
    \"style\":\"${13}\"
  }" -XPOST
