# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:0.0.0.0"
port:           "_env:PORT:1682"
approot:        "_env:APPROOT:https://leuro.adarq.org"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false
#
# send-mail: true
# allow-dummy-auth: false
# force-ssl: true

database:
  user:     "_env:PGUSER:postgres"
  password: "_env:PGPASS:"
  host:     "_env:PGHOST:127.0.0.1"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:leuro"
  poolsize: "_env:PGPOOLSIZE:10"

copyright: leuro (C)
#analytics: UA-YOURCODE

env: "production"

redis-host: "adarq.internal"
