#!/bin/bash

[ $# == 7 ] || { echo 'usage: post <bucket_id> <name> <desc> <leurons> <resources> <categories> <filters>' && exit 1; }

curlx-json buckets/${1} -d \
  "{ \
  \"name\":\"${2}\", \
  \"desc\":\"${3}\", \
  \"leurons\":[${4}], \
  \"resources\":[${5}], \
  \"categories\":[${6}], \
  \"filters\":[${7}] \
  }" -XPUT

# ./api/buckets/put 6 name4 desc 1,3,4,8 2,4 \"3\" 8
